//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.17 at 11:22:55 AM EEST 
//


package com.viewer4d.config.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.viewer4d.config.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Figure_QNAME = new QName("tests:4DViewer:PlainFigureConfig", "figure");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.viewer4d.config.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EdgeType }
     * 
     */
    public EdgeType createEdgeType() {
        return new EdgeType();
    }

    /**
     * Create an instance of {@link VertexType }
     * 
     */
    public VertexType createVertexType() {
        return new VertexType();
    }

    /**
     * Create an instance of {@link FaceType }
     * 
     */
    public FaceType createFaceType() {
        return new FaceType();
    }

    /**
     * Create an instance of {@link FigureType }
     * 
     */
    public FigureType createFigureType() {
        return new FigureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FigureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "tests:4DViewer:PlainFigureConfig", name = "figure")
    public JAXBElement<FigureType> createFigure(FigureType value) {
        return new JAXBElement<FigureType>(_Figure_QNAME, FigureType.class, null, value);
    }

}
